name: Earthly +build

on:
  push:
    branches:
      - '**' # Run on all branches

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.0
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        # echo "$SSH_PRIVATE_KEY" | DISPLAY=None ssh-add - > /dev/null
    - name: Run build
      run: earthly --ci +build
